check.cgi:sign.cpp sql_connection_pool.cpp sql_connection_pool.h
	g++ -o check.cgi sign.cpp sql_connection_pool.cpp sql_connection_pool.h -lmysqlclient
#check_connect_mysql.o:check_connect_mysql.cpp
#	g++ -c check_connect_mysql.cpp
#connection_pool.o:connection_pool.cpp connection_pool.h
#	g++ -c connection_pool.cpp connection_pool.h
#clean:
#	rm -rf *.o *.h.gch
